drone_num:                  3.0

init_pos_0_x:               -10.0
init_pos_0_y:               0.0
init_pos_0_z:               5.0

init_pos_1_x:               -10.0
init_pos_1_y:               -3.0
init_pos_1_z:               5.0

init_pos_2_x:               -10.0
init_pos_2_y:               3.0
init_pos_2_z:               5.0

init_vel_0_x:               2.0
init_vel_0_y:               0.0
init_vel_0_z:               0.0

init_vel_1_x:               2.0
init_vel_1_y:               0.0
init_vel_1_z:               0.0

init_vel_2_x:               2.0
init_vel_2_y:               0.0
init_vel_2_z:               0.0

des_theta_0_x:              1.0
des_theta_0_y:              0.0
des_theta_0_z:              0.0

des_theta_1_x:              0.707
des_theta_1_y:              -0.707
des_theta_1_z:              0.0

des_theta_2_x:              0.707
des_theta_2_y:              0.707
des_theta_2_z:              0.0


####################################################################
# drone_num:                  2.0

# init_pos_0_x:               0.0
# init_pos_0_y:               -6.0
# init_pos_0_z:               5.0

# init_pos_1_x:               0.0
# init_pos_1_y:               6.0
# init_pos_1_z:               5.0

# init_vel_0_x:               2.0
# init_vel_0_y:               0.0
# init_vel_0_z:               0.0

# init_vel_1_x:               2.0
# init_vel_1_y:               0.0
# init_vel_1_z:               0.0

# des_theta_0_x:              0.707
# des_theta_0_y:              -0.707
# des_theta_0_z:              0.0

# des_theta_1_x:              0.707
# des_theta_1_y:              0.707
# des_theta_1_z:              0.0

###########################################################
# drone_num:                  1.0

# init_pos_0_x:               0.0
# init_pos_0_y:               0.0
# init_pos_0_z:               5.0

# init_vel_0_x:               0.5
# init_vel_0_y:               0.0
# init_vel_0_z:               0.0

# des_theta_0_x:              0.707
# des_theta_0_y:              0.707
# des_theta_0_z:              0.0
